### ISSUE TITLE
Invalid references to the documentation of the service

### ISSUE THREAD

**Issue by fmrsabino** [safe-global/safe-gateway-typescript-sdk#133]
Since the service was migrated to Node.js, the documentation that was available under https://safe.global/safe-client-gateway ceased to exist.

The documentation that was available there was generated by Rust's `doc` tool. Since this no longer applies to the new project an alternative needs to be considered. 

As for what is available right now: Swagger already provides the types being used on each endpoint as well as the respective structure. The OpenAPI specification in JSON format can be found under: https://safe-client.safe.global/-json

**Comment by fmrsabino** [comment]
Some references still exist as a comment in the codebase – https://github.com/safe-global/safe-gateway-typescript-sdk/blob/2d4d7ee972dee21d00ed553b23a85fc92da3cb9b/src/types/transactions.ts#L66

(not addressed in https://github.com/safe-global/safe-gateway-typescript-sdk/commit/a816d76cf30890523f75359b7c26513f8565d5d1)

**Comment by katspaugh** [comment]
Thanks, removed!
